import {
  readTestState,
  test,
  expect,
  spawnFixture as spawn,
} from "../playwright.mjs";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
test("sidebar drag browser", async ({ page: runnerPage }) => {
  test.setTimeout(600000);
  const root = resolve(import.meta.dirname, "../../../../../../");
  const stateDir = await mkdtemp(join(tmpdir(), "studio-sidebar-drag-"));
  console.log("Sidebar fixture state retained after worker cleanup:", stateDir);
  const proc = spawn(
    "python3",
    [
      "-B",
      join(
        root,
        "workspaces/runtime/apps/server/tests/sidebar-drag-fixture.py",
      ),
      stateDir,
    ],
    { stdio: ["ignore", "pipe", "pipe"] },
  );
  let log = "";
  proc.stderr.on("data", (d) => (log += d));
  try {
    const port = await new Promise((resolve, reject) => {
      proc.stdout.once("data", (d) => resolve(Number(String(d).trim())));
      proc.once("exit", () => reject(Error(log)));
    });
    const url = `http://127.0.0.1:${port}`;
    const state = async () => await readTestState(url);
    const initial = await state();
    const agents = Object.fromEntries(
      initial.runtime.agents.map((a) => [a.name, a]),
    );
    const projectPath = initial.runtime.projects.find(
      (p) => p.name === "Project A",
    ).path;
    const projectPaths = Object.fromEntries(
      initial.runtime.projects.map((row) => [row.name, row.path]),
    );
    const token = initial.token;
    const post = async (body) => {
      const r = await fetch(url + "/api/peer-teams", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Canvas-Token": token,
          Origin: url,
        },
        body: JSON.stringify(body),
      });
      return { status: r.status, body: await r.json() };
    };
    const unauthorized = await fetch(url + "/api/peer-teams", {
      method: "POST",
      headers: { "Content-Type": "application/json", Origin: url },
      body: JSON.stringify({ action: "convert" }),
    });
    assert.equal(unauthorized.status, 403);
    const page = runnerPage;
    await page.setViewportSize({ width: 1440, height: 900 });
    page.setDefaultTimeout(30000);
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(url);
    console.log("Sidebar fixture loaded");
    const project = (name) =>
      page.locator(".sidebar-project").filter({
        has: page.locator(".project-tree-toggle").filter({ hasText: name }),
      });
    const projectA = page.locator(`[data-project-path="${projectPath}"]`);
    const row = (name) => page.locator(`[data-chat="${agents[name].id}"]`);
    await projectA.getByRole("button", { name: /^Show old \(\d+\)$/ }).click();
    await row("Destination").waitFor();
    await row("Destination").click();
    console.log("Sidebar initial selection ready");
    // Native HTML drag events generated by actual mouse movement. No dispatchEvent.
    let scrolledDrags = 0;
    const drag = async (from, to, edge = 0.5) => {
      await from.scrollIntoViewIfNeeded();
      const a = await from.boundingBox();
      assert.ok(a);
      const sourceY = a.y + a.height / 2;
      assert.ok(
        sourceY > 0 && sourceY < page.viewportSize().height,
        "The drag starts inside the normal-height window",
      );
      if (
        await from.evaluate(
          (element) => element.closest("#chat-list").scrollTop > 0,
        )
      )
        scrolledDrags++;
      await page.mouse.move(a.x + 18, sourceY);
      await page.mouse.down();
      await page.mouse.move(a.x + 22, sourceY + 9, { steps: 6 });
      // Keep the source visible until Chromium starts the native drag.
      await to.scrollIntoViewIfNeeded();
      const b = await to.boundingBox();
      assert.ok(b);
      const destinationY = b.y + b.height * edge;
      assert.ok(
        destinationY > 0 && destinationY < page.viewportSize().height,
        "The drop is inside the normal-height window",
      );
      await page.mouse.move(b.x + 18, destinationY, { steps: 20 });
      // Chromium completes native drag recognition on the second destination move.
      await page.mouse.move(b.x + 20, destinationY, { steps: 3 });
      await page.mouse.up();
    };
    const settledOrder = () =>
      page.waitForFunction(
        () =>
          !Object.keys(localStorage).some(
            (key) =>
              key.startsWith("codex-sidebar-order:") &&
              key.endsWith(":pending"),
          ),
      );
    const projects = () =>
      page
        .locator(
          ".sidebar-project > .project-tree-heading > .project-tree-toggle span",
        )
        .allTextContents();
    assert.deepEqual(await projects(), ["Project A", "Project B", "Project C"]);
    const reorderResponse = page.waitForResponse((response) => {
      const request = response.request();
      const order = request.postDataJSON()?.groups?.projects;
      return (
        new URL(response.url()).pathname === "/api/projects" &&
        request.method() === "POST" &&
        request.postDataJSON()?.action === "reorder" &&
        Array.isArray(order) &&
        order[0] === projectPaths["Project C"]
      );
    });
    await drag(
      project("Project C").locator(
        "> .project-tree-heading > .project-tree-toggle",
      ),
      project("Project A").locator(
        "> .project-tree-heading > .project-tree-toggle",
      ),
      0.1,
    );
    await page.waitForFunction(
      () =>
        document.querySelector(".sidebar-project > .project-tree-heading span")
          ?.textContent === "Project C",
    );
    assert.deepEqual(await projects(), ["Project C", "Project A", "Project B"]);
    console.log("Project pointer drag passed");
    const response = await reorderResponse;
    const responseBody = await response.json();
    const expectedOrder = [
      projectPaths["Project C"],
      projectPaths["Project A"],
      projectPaths["Project B"],
    ];
    assert.ok(
      responseBody._syncEntities?.some((entity) => {
        if (entity.id !== "entity:workspace:current") return false;
        const payload = JSON.parse(entity.payload);
        return (
          JSON.stringify(payload.value.sidebarOrder.groups.projects) ===
          JSON.stringify(expectedOrder)
        );
      }),
      "The reorder response carries the updated workspace entity",
    );
    const workspaceCache = () =>
      page.evaluate(async () => {
        const names = (await indexedDB.databases())
          .map((database) => database.name)
          .filter((name) => name?.startsWith("rxdb-dexie-studio"));
        return Promise.all(
          names.map(
            (name) =>
              new Promise((resolve) => {
                const request = indexedDB.open(name);
                request.onerror = () => resolve({ name, error: true });
                request.onsuccess = () => {
                  const db = request.result;
                  const tx = db.transaction("docs", "readonly");
                  const rows = tx.objectStore("docs").getAll();
                  rows.onsuccess = () => {
                    const workspace = rows.result.find(
                      (row) => row.id === "entity:workspace:current",
                    );
                    resolve({
                      name,
                      workspace: workspace
                        ? JSON.parse(workspace.payload).value.sidebarOrder
                        : null,
                    });
                    db.close();
                  };
                };
              }),
          ),
        );
      });
    await expect
      .poll(async () =>
        (await workspaceCache()).some(
          (entry) =>
            JSON.stringify(entry.workspace?.groups?.projects) ===
            JSON.stringify(expectedOrder),
        ),
      )
      .toBe(true);
    await settledOrder();
    await page.reload();
    await row("Destination").waitFor();
    assert.deepEqual(await projects(), ["Project C", "Project A", "Project B"]);
    const topItems = () =>
      projectA
        .locator(".project-chats > [data-sidebar-item]")
        .evaluateAll((nodes) =>
          nodes
            .filter((n) => !n.querySelector(".chat-pin"))
            .map(
              (n) =>
                n.querySelector(".project-tree-toggle span,.row-copy strong")
                  ?.textContent,
            ),
        );
    const folderA = projectA
      .locator("[data-folder-id]")
      .filter({
        has: page
          .locator(".project-tree-toggle")
          .filter({ hasText: "Folder A" }),
      })
      .locator("> .project-tree-heading > .project-tree-toggle");
    const team = projectA.locator(".peer-team-toggle");
    assert.equal((await topItems())[0], "Team A");
    await drag(folderA, team, 0.1);
    await page.waitForFunction(
      (path) =>
        Array.from(
          document.querySelectorAll(
            `[data-project-path="${path}"] .project-chats > [data-sidebar-item]`,
          ),
        )
          .filter((n) => !n.querySelector(".chat-pin"))[0]
          ?.querySelector(".project-tree-toggle span")?.textContent ===
        "Folder A",
      projectPath,
    );
    assert.equal((await topItems())[0], "Folder A");
    await settledOrder();
    await team.press("Alt+ArrowUp");
    await settledOrder();
    await expect.poll(async () => (await topItems())[0]).toBe("Team A");
    await settledOrder();
    await team.press("Alt+ArrowDown");
    await settledOrder();
    await expect.poll(async () => (await topItems())[1]).toBe("Team A");
    await settledOrder();
    await page.reload();
    await row("Destination").waitFor();
    assert.equal((await topItems())[0], "Folder A");
    // Loose chats share the same order group with folders and teams.
    await drag(row("Destination"), folderA, 0.1);
    await page.waitForFunction(
      (path) =>
        Array.from(
          document.querySelectorAll(
            `[data-project-path="${path}"] .project-chats > [data-sidebar-item]`,
          ),
        )
          .filter((n) => !n.querySelector(".chat-pin"))[0]
          ?.querySelector(".row-copy strong")?.textContent === "Destination",
      projectPath,
    );
    assert.equal((await topItems())[0], "Destination");
    await settledOrder();
    await page.reload();
    await row("Destination").waitFor();
    await expect.poll(async () => (await topItems())[0]).toBe("Destination");
    // Compact mode keeps peer teams, pinned, recent, unread and running chats.
    await projectA.locator("> .project-tree-heading").hover();
    await page
      .getByRole("button", {
        name: "Options for project Project A",
        exact: true,
      })
      .click();
    await page.getByRole("menuitem", { name: "Hide old", exact: true }).click();
    await row("Old hidden").waitFor({ state: "hidden" });
    assert.equal(await row("Old folder hidden").count(), 0);
    for (const name of [
      "Team source",
      "Team peer",
      "Pinned",
      "Recent",
      "Unread",
      "Running",
    ])
      assert.equal(await row(name).isVisible(), true, name);
    const compactOrder = await topItems();
    await projectA.locator("> .project-tree-heading").hover();
    await page
      .getByRole("button", {
        name: "Options for project Project A",
        exact: true,
      })
      .click();
    await expect(
      page.getByRole("menuitem", { name: "Show old (2)", exact: true }),
    ).toBeVisible();
    await page.keyboard.press("Escape");
    await settledOrder();
    await team.press("Alt+ArrowDown");
    await settledOrder();
    await expect
      .poll(async () => (await topItems()).indexOf("Team A"))
      .toBe(compactOrder.indexOf("Team A") + 1);
    await settledOrder();
    await team.press("Alt+ArrowUp");
    await settledOrder();
    await expect.poll(topItems).toEqual(compactOrder);
    await expect(
      projectA.getByRole("button", { name: "Show old (2)", exact: true }),
    ).toBeVisible();
    await settledOrder();
    await page.reload();
    await row("Team source").waitFor();
    assert.equal(await row("Old hidden").count(), 0);
    await page
      .getByRole("searchbox", { name: "Filter projects and chats" })
      .fill("Old hidden");
    await row("Old hidden").waitFor();
    await page
      .getByRole("searchbox", { name: "Filter projects and chats" })
      .fill("");
    await row("Old hidden").waitFor({ state: "hidden" });
    await page
      .getByRole("button", { name: "Show old (2)", exact: true })
      .click();
    await row("Old hidden").waitFor();
    await settledOrder();
    await page.reload();
    await row("Destination").waitFor();
    assert.equal(await row("Old hidden").isVisible(), true);
    // The drop prepares a confirmation; cancellation applies no backend change.
    await drag(row("Team source"), row("Destination"));
    let dialog = page.getByRole("dialog", { name: "Make chat a subagent" });
    await dialog.waitFor();
    assert.ok((await dialog.textContent()).includes("Team source"));
    assert.ok((await dialog.textContent()).includes("Destination"));
    assert.ok((await dialog.textContent()).includes("account, model"));
    await page.keyboard.press("Escape");
    await dialog.waitFor({ state: "hidden" });
    assert.equal(
      (await state()).runtime.agents.find(
        (a) => a.id === agents["Team source"].id,
      ).isLead,
      true,
    );
    // Busy refusal is delivered from the actual backend action.
    await drag(row("Team source"), row("Running"));
    await page
      .getByRole("button", { name: "Make subagent", exact: true })
      .click();
    await page
      .getByRole("alert")
      .filter({ hasText: "finish the active or queued turn" })
      .waitFor();
    await page.keyboard.press("Escape");
    await dialog.waitFor({ state: "hidden" });
    // Lose the success response, then retry the exact body. The move applies once.
    const conversionBodies = [];
    let lost = true;
    await page.route("**/api/peer-teams", async (route) => {
      const body = route.request().postDataJSON();
      if (body.action !== "convert") return route.continue();
      conversionBodies.push(body);
      const response = await route.fetch();
      if (lost) {
        lost = false;
        assert.equal(response.status(), 200);
        return route.abort("failed");
      }
      await route.fulfill({ response });
    });
    await drag(row("Team source"), row("Destination"));
    await page
      .getByRole("button", { name: "Make subagent", exact: true })
      .click();
    await page
      .getByRole("button", { name: "Retry saved request", exact: true })
      .waitFor();
    await settledOrder();
    await page.reload();
    await page
      .getByRole("button", { name: "Retry saved request", exact: true })
      .waitFor();
    await page
      .getByRole("button", { name: "Retry saved request", exact: true })
      .click();
    await dialog.waitFor({ state: "hidden" });
    assert.equal(conversionBodies.length, 2);
    assert.deepEqual(conversionBodies[0], conversionBodies[1]);
    await row("Team source").waitFor({ state: "hidden" });
    const final = await state();
    const moved = final.runtime.agents.find(
      (a) => a.id === agents["Team source"].id,
    );
    assert.equal(moved.parentId, agents.Destination.id);
    assert.equal(moved.rootId, agents.Destination.id);
    assert.equal(moved.isLead, false);
    assert.equal(
      final.runtime.agents.find((a) => a.name === "Original worker").rootId,
      agents.Destination.id,
    );
    assert.equal(await page.locator("[data-peer-team]").count(), 0);
    await settledOrder();
    await page.reload();
    await row("Destination").waitFor();
    assert.equal(await row("Team source").count(), 0);
    const repeated = await post(conversionBodies[0]);
    assert.equal(repeated.status, 200);
    const finalState = await state();
    assert.equal(
      finalState.runtime.agents.find((a) => a.id === moved.id).epoch,
      moved.epoch,
    );
    assert.ok(
      scrolledDrags > 0,
      "The regression exercises drag in a scrolled list",
    );
    assert.equal(page.viewportSize().height, 900);
    expect(errors).toEqual([]);
    console.log(
      "Sidebar pointer drag: mixed order, keyboard, project persistence, compact mode/search, confirmation, busy refusal, lost-response retry and conversion sync PASS",
    );
  } catch (error) {
    console.error("Fixture errors:", log);
    throw error;
  }
});
