#!/usr/bin/env python3
"""Generate renderer entity DTO declarations from codex_sync_entities field sets."""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from codex_sync_entities import AGENT_FIELDS, COLLECTION_FIELDS

OUTPUT = ROOT / "web/src/generatedEntityTypes.ts"
TYPE_NAMES = {"peerTeam": "PeerTeam"}


def render():
    collections = {"agent": AGENT_FIELDS, **COLLECTION_FIELDS}
    lines = ["// Generated by scripts/generate-entity-types.py; do not edit."]
    for collection in sorted(collections):
        name = TYPE_NAMES.get(collection, "".join(part.title() for part in collection.split("_"))) + "EntityDto"
        lines.extend((f"export interface {name} {{", *(
            f"  {field}{'' if field == 'id' else '?'}: {'string' if field == 'id' else 'any'};"
            for field in sorted(collections[collection])
        ), "}", ""))
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked-in file is stale")
    args = parser.parse_args()
    expected = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else ""
    if args.check:
        if current != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run python3 scripts/generate-entity-types.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
