// Generated by scripts/generate-entity-types.py; do not edit.
export interface AgentEntityDto {
  accountKey?: any;
  accountTransfer?: any;
  activity?: any;
  agentMode?: any;
  agentModeRevision?: any;
  agentModeSupported?: any;
  archived?: any;
  autoWake?: any;
  canSend?: any;
  compactions?: any;
  concurrency?: any;
  contextUsage?: any;
  created?: any;
  cwd?: any;
  daybreakEnabled?: any;
  deletedAt?: any;
  effort?: any;
  empty?: any;
  error?: any;
  fastMode?: any;
  hasApproval?: any;
  hasQuestion?: any;
  hasUnread?: any;
  id: string;
  inFlight?: any;
  isLead?: any;
  kind?: any;
  lastAnswer?: any;
  lastCompletedTurn?: any;
  lastReadAt?: any;
  launcherAlive?: any;
  model?: any;
  name?: any;
  nativeError?: any;
  nativeRelease?: any;
  nativeStatus?: any;
  nativeThreadBlock?: any;
  nextTurnSettingsSupported?: any;
  orchestratorId?: any;
  orchestratorName?: any;
  overview?: any;
  panelDataVersion?: any;
  panelVersion?: any;
  parentId?: any;
  parkedEvent?: any;
  pendingSettings?: any;
  pendingSettingsAccountKey?: any;
  pinned?: any;
  projectFolder?: any;
  projectFolderRevision?: any;
  provider?: any;
  queuedSettings?: any;
  quickCreate?: any;
  readStateSupported?: any;
  retryAt?: any;
  reviewDefaults?: any;
  role?: any;
  rootId?: any;
  sharedRoomId?: any;
  source?: any;
  startAttempt?: any;
  status?: any;
  statusDetail?: any;
  subagentConcurrencyVersion?: any;
  tail?: any;
  threadId?: any;
  tokensUsed?: any;
  turnId?: any;
  turnStatus?: any;
  unreadCount?: any;
  updated?: any;
  voiceState?: any;
  workerDefaults?: any;
  worktree?: any;
  yoloMode?: any;
}

export interface ChatEntityDto {
  id: string;
  kind?: any;
  lastMessageAt?: any;
  members?: any;
  messageCount?: any;
  name?: any;
  tail?: any;
}

export interface ComplaintEntityDto {
  author?: any;
  authorName?: any;
  created?: any;
  id: string;
  leadDeleted?: any;
  leadId?: any;
  leadName?: any;
  leadStopped?: any;
  needsResponse?: any;
  readAt?: any;
  recipient?: any;
  status?: any;
  title?: any;
  version?: any;
}

export interface EdgeEntityDto {
  id: string;
  kind?: any;
  source?: any;
  target?: any;
}

export interface EventEntityDto {
  agent?: any;
  created?: any;
  error?: any;
  id: string;
  kind?: any;
  status?: any;
}

export interface MonitorEntityDto {
  agent?: any;
  bytes?: any;
  cancelRequested?: any;
  command?: any;
  created?: any;
  cwd?: any;
  durationMs?: any;
  error?: any;
  exitCode?: any;
  finished?: any;
  id: string;
  interactive?: any;
  log?: any;
  name?: any;
  outputTruncated?: any;
  processId?: any;
  ruleId?: any;
  status?: any;
  stdinCloseRequested?: any;
  stdinClosed?: any;
  stdinError?: any;
  tail?: any;
  timeout_ms?: any;
}

export interface PeerTeamEntityDto {
  id: string;
  members?: any;
  name?: any;
  projectPath?: any;
}

export interface ProjectEntityDto {
  accountKey?: any;
  accountKeys?: any;
  accountRevision?: any;
  created?: any;
  folders?: any;
  id: string;
  name?: any;
  organizationRevision?: any;
  path?: any;
  peerTeamsRevision?: any;
}

export interface RequestEntityDto {
  agent?: any;
  at?: any;
  created?: any;
  createdAt?: any;
  deferred?: any;
  error?: any;
  id: string;
  method?: any;
  params?: any;
  result?: any;
  status?: any;
  title?: any;
  updated?: any;
  updatedAt?: any;
}

export interface RoomEntityDto {
  id: string;
  kind?: any;
  lastMessage?: any;
  members?: any;
  name?: any;
  peerTeamId?: any;
  peerTeamName?: any;
  projectPath?: any;
  radio?: any;
  rootId?: any;
  updated?: any;
  userHidden?: any;
}

export interface RuleEntityDto {
  agent?: any;
  description?: any;
  enabled?: any;
  id: string;
  name?: any;
}

export interface TaskEntityDto {
  agent?: any;
  bytes?: any;
  cancelRequested?: any;
  command?: any;
  created?: any;
  cwd?: any;
  durationMs?: any;
  exitCode?: any;
  finished?: any;
  id: string;
  interactive?: any;
  kind?: any;
  log?: any;
  name?: any;
  outputTruncated?: any;
  processId?: any;
  query?: any;
  status?: any;
  stdinCloseRequested?: any;
  stdinClosed?: any;
  stdinError?: any;
  timeout_ms?: any;
  turnId?: any;
}

export interface WorkEntityDto {
  agent?: any;
  id: string;
  rootId?: any;
  status?: any;
  title?: any;
}

export interface WorkspaceEntityDto {
  connected?: any;
  nativeNotices?: any;
  peerTeamsVersion?: any;
  projectOrganizationVersion?: any;
  rateLimits?: any;
  rateLimitsByAccount?: any;
  sidebarOrder?: any;
  stateDir?: any;
  tasksHistoryLimit?: any;
}
